version: 2
jobs:
  build:
    docker:
      - image: seesharprun/content-generation-pandoc:0.1.0
    working_directory: ~/source/
    steps:
      - checkout
      - run:
          name: Test Pandoc
          command: pandoc -v
      - run:
          name: Test PDFLatex
          command: pdflatex -v
      - run:
          working_directory: ~/source/.build
          name: Install NPM Packages
          command: npm install  
      - save_cache:
          key: dependency-cache-{{ checksum "~/source/.build/package.json" }}
          paths:
            - ~/source/.build/node_modules
      - run:
          working_directory: ~/source/.build
          name: Build Lab Content
          command: node package.js
      - store_artifacts:
          path: ~/source/.build/out
